env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org,direct

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
archives:
  -
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md


checksum:
  name_template: 'checksums.txt'
