version: 2

env:
  - GO111MODULE=on

gomod:
  proxy: true

project_name: platys

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
  - format: zip
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"


